/*
 * Process Services Enterprise API
 * Provides access to the complete features provided by Alfresco Process Services powered by Activiti.  You can use this API to integrate Alfresco Process Services with external applications.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.activiti.engine.remote.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DataSourceConfigRepresentation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-26T11:35:07.343+01:00")
public class DataSourceConfigRepresentation {
  @SerializedName("driverClass")
  private String driverClass = null;

  @SerializedName("jdbcUrl")
  private String jdbcUrl = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("username")
  private String username = null;

  public DataSourceConfigRepresentation driverClass(String driverClass) {
    this.driverClass = driverClass;
    return this;
  }

   /**
   * Get driverClass
   * @return driverClass
  **/
  @ApiModelProperty(value = "")
  public String getDriverClass() {
    return driverClass;
  }

  public void setDriverClass(String driverClass) {
    this.driverClass = driverClass;
  }

  public DataSourceConfigRepresentation jdbcUrl(String jdbcUrl) {
    this.jdbcUrl = jdbcUrl;
    return this;
  }

   /**
   * Get jdbcUrl
   * @return jdbcUrl
  **/
  @ApiModelProperty(value = "")
  public String getJdbcUrl() {
    return jdbcUrl;
  }

  public void setJdbcUrl(String jdbcUrl) {
    this.jdbcUrl = jdbcUrl;
  }

  public DataSourceConfigRepresentation password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public DataSourceConfigRepresentation username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataSourceConfigRepresentation dataSourceConfigRepresentation = (DataSourceConfigRepresentation) o;
    return Objects.equals(this.driverClass, dataSourceConfigRepresentation.driverClass) &&
        Objects.equals(this.jdbcUrl, dataSourceConfigRepresentation.jdbcUrl) &&
        Objects.equals(this.password, dataSourceConfigRepresentation.password) &&
        Objects.equals(this.username, dataSourceConfigRepresentation.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(driverClass, jdbcUrl, password, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataSourceConfigRepresentation {\n");
    
    sb.append("    driverClass: ").append(toIndentedString(driverClass)).append("\n");
    sb.append("    jdbcUrl: ").append(toIndentedString(jdbcUrl)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

