/*
 * Process Services Enterprise API
 * Provides access to the complete features provided by Alfresco Process Services powered by Activiti.  You can use this API to integrate Alfresco Process Services with external applications.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.activiti.engine.remote.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.activiti.engine.remote.client.model.TaskFilterRepresentation;

/**
 * UserTaskFilterRepresentation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-26T11:35:07.343+01:00")
public class UserTaskFilterRepresentation {
  @SerializedName("appId")
  private Long appId = null;

  @SerializedName("filter")
  private TaskFilterRepresentation filter = null;

  @SerializedName("icon")
  private String icon = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("recent")
  private Boolean recent = null;

  public UserTaskFilterRepresentation appId(Long appId) {
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @ApiModelProperty(value = "")
  public Long getAppId() {
    return appId;
  }

  public void setAppId(Long appId) {
    this.appId = appId;
  }

  public UserTaskFilterRepresentation filter(TaskFilterRepresentation filter) {
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @ApiModelProperty(value = "")
  public TaskFilterRepresentation getFilter() {
    return filter;
  }

  public void setFilter(TaskFilterRepresentation filter) {
    this.filter = filter;
  }

  public UserTaskFilterRepresentation icon(String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }

  public UserTaskFilterRepresentation id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserTaskFilterRepresentation index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @ApiModelProperty(value = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public UserTaskFilterRepresentation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserTaskFilterRepresentation recent(Boolean recent) {
    this.recent = recent;
    return this;
  }

   /**
   * Get recent
   * @return recent
  **/
  @ApiModelProperty(value = "")
  public Boolean isRecent() {
    return recent;
  }

  public void setRecent(Boolean recent) {
    this.recent = recent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserTaskFilterRepresentation userTaskFilterRepresentation = (UserTaskFilterRepresentation) o;
    return Objects.equals(this.appId, userTaskFilterRepresentation.appId) &&
        Objects.equals(this.filter, userTaskFilterRepresentation.filter) &&
        Objects.equals(this.icon, userTaskFilterRepresentation.icon) &&
        Objects.equals(this.id, userTaskFilterRepresentation.id) &&
        Objects.equals(this.index, userTaskFilterRepresentation.index) &&
        Objects.equals(this.name, userTaskFilterRepresentation.name) &&
        Objects.equals(this.recent, userTaskFilterRepresentation.recent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, filter, icon, id, index, name, recent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserTaskFilterRepresentation {\n");
    
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    recent: ").append(toIndentedString(recent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

